
version: '3.8'
services:
  main_server:
    build: .
    command: uvicorn backend.main_server:app --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"
  ai_server:
    build: .
    command: uvicorn backend.ai_server:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
